// demos/react/src/components/AppForm.jsx
import { useEffect, useState } from 'react';
import useDebounce from '../hooks/useDebounce';
import { run } from '@zootools/email-spell-checker';

function AppForm() {
  const [email, setEmail] = useState('');
  const [suggestedEmail, setSuggestedEmail] = useState({});
  const [forceCloseModal, setForceCloseModal] = useState(false);

  let debouncedEmail = useDebounce(email, 400);

  useEffect(() => {
    const suggested = run({
      email: debouncedEmail,
    });

    if (suggested) {
      setSuggestedEmail(suggested);
    } else {
      setForceCloseModal(true);
      setTimeout(() => {
        setSuggestedEmail({});
      }, 500);
    }
  }, [debouncedEmail]);

  const handleEmailChange = val => {
    setEmail(val);
  };

  const handleFixEmail = () => {
    setForceCloseModal(true);

    setTimeout(() => {
      setEmail(suggestedEmail.full);
    }, 500);

    setTimeout(() => {
      setForceCloseModal(false);
    }, 900);
  };

  const handleClearSuggestedEmail = e => {
    e.preventDefault();

    setForceCloseModal(true);
    setTimeout(() => {
      setSuggestedEmail({});
      setForceCloseModal(false);
    }, 500);
  };

  return (
    <form id="signup-form">
      <label>Username*</label>
      <input id="username-input" className="input" />
      <label>Email*</label>
      <div id="email-container">
        <i id="email-icon" className="fa-regular fa-envelope fa-lg"></i>
        <input
          id="email-input"
          className="input"
          onChange={e => handleEmailChange(e.target.value)}
          value={email}
        />
      </div>
      <div
        id="email-warning-container"
        className={`${suggestedEmail.full && !forceCloseModal ? 'view' : null}`}
      >
        <button id="warning-dismiss" onClick={handleClearSuggestedEmail}>
          X
        </button>
        <span id="warning" onClick={handleFixEmail}>
          <span id="warning-text">Did you mean</span>
          <span id="warning-email">{suggestedEmail.full}?</span>
        </span>
      </div>
      <label>Password*</label>
      <input id="password-input" className="input" />
    </form>
  );
}

export default AppForm;

// demos/vue/src/components/AppForm.vue
<template>
  <form id="signup-form">
    <label>Username*</label>
    <input id="username-input" class="input" />
    <label>Email*</label>
    <div id="email-container">
      <i id="email-icon" class="fa-regular fa-envelope fa-lg"></i>
      <input id="email-input" className="input" v-model="email" />
    </div>
    <div
      id="email-warning-container"
      :class="{ view: suggestedEmail.full && !forceCloseModal }"
    >
      <button id="warning-dismiss" @click="dismissWarning">X</button>
      <span id="warning" @click="setEmailToSuggested">
        <span id="warning-text">Did you mean</span>
        <span id="warning-email">{{ suggestedEmail.full }}?</span>
      </span>
    </div>
    <label>Password*</label>
    <input id="password-input" className="input" />
  </form>
</template>
<script setup>
import { ref, watch } from 'vue';
import { run } from '@zootools/email-spell-checker';

const email = ref('');
const suggestedEmail = ref({});
const forceCloseModal = ref(false);

const setEmailToSuggested = () => {
  forceCloseModal.value = true;
  email.value = suggestedEmail.value.full;
  setTimeout(() => {
    suggestedEmail.value = {};
    forceCloseModal.value = false;
  }, 600);
};

const dismissWarning = e => {
  e.preventDefault();

  forceCloseModal.value = true;
  setTimeout(() => {
    suggestedEmail.value = {};
    forceCloseModal.value = false;
  }, 600);
};

let timer;
watch(email, () => {
  if (timer) {
    clearTimeout(timer);
  }

  timer = setTimeout(() => {
    const suggested = run({
      email: email.value,
    });

    if (suggested) {
      suggestedEmail.value = suggested;
    } else {
      forceCloseModal.value = true;
      setTimeout(() => {
        suggestedEmail.value = {};
        forceCloseModal.value = false;
      }, 600);
    }
  }, 500);
});
</script>
